default_agent: scottleduc_consultant
agents:
  scottleduc_simple_agent:
    name: scottleduc_simple_agent
    entrypoint: simple_agent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: /Users/scottleduc/Projects/consulting-website/chatbot
    aws:
      execution_role: arn:aws:iam::441383083571:role/BedrockAgentCoreRuntimeRole
      execution_role_auto_create: true
      account: '441383083571'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: scottleduc_simple_agent_mem-yV76oFDp4P
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:441383083571:memory/scottleduc_simple_agent_mem-yV76oFDp4P
      memory_name: scottleduc_simple_agent_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
  scottleduc_consultant:
    name: scottleduc_consultant
    entrypoint: /Users/scottleduc/Projects/consulting-website/chatbot/app.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_12
    platform: linux/arm64
    container_runtime: null
    source_path: /Users/scottleduc/Projects/consulting-website/chatbot
    aws:
      execution_role: arn:aws:iam::441383083571:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-855e130581
      execution_role_auto_create: false
      account: '441383083571'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: scottleduc-consulting-kb
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: scottleduc_consultant-vKDki47sNm
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:441383083571:runtime/scottleduc_consultant-vKDki47sNm
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: scottleduc_consultant_mem-er6lzH3Wp1
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:441383083571:memory/scottleduc_consultant_mem-er6lzH3Wp1
      memory_name: scottleduc_consultant_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
